### PR TITLE
Added scripts to run VBS

### PR DESCRIPTION
**Pull request by bingranw**
- Updated VBSProducer.py
- Added script to run VBSProducer
- Added NanoAODv7 samples

### CODE REVIEW

**Comment by yhaddad** [comment]
Did you change anything on the VBSProducer in the `python` directory? If so you could include that in this PR?

**Comment by yhaddad** [comment]
Also FYI, usually, you can give a short description of the changes you made. This helps the maintainer understand what to look for in the code.

**Comment by bingranw** [comment]
Yes, I changed something in the VBSProducer, but the changes are not final.

**Comment by yhaddad** [comment]
I am accepting this PR on the mean time. You can still send another PR when you have new devs.

**Pull request merged**
